version: '3.8'

services:
  producer:
    image: producer-service:latest
    ports:
      - "6969:6969"
    environment:
      - KAFKA_BROKERS=kafka-mumbai:29092,kafka-pune:29092,kafka-delhi:29092
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    networks:
      - kafka-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  consumer:
    image: consumer-service:latest
    environment:
      - KAFKA_BROKERS=kafka-mumbai:29092,kafka-pune:29092,kafka-delhi:29092
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    networks:
      - kafka-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  kafka-network:
    external: true
