version: '3.8'

services:
  kafka-mumbai:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka-mumbai
    ports:
      - "29092:29092"
      - "9093:9093"  
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-mumbai:9093,2@kafka-pune:9093,3@kafka-delhi:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9101
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-mumbai:29092,EXTERNAL://localhost:9101
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      CLUSTER_ID: "XxLmcxwkQpieZydFQPRnzw"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-mumbai-data:/var/lib/kafka/data
    networks:
      - kafka-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  kafka-pune:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka-pune
    ports:
      - "29093:29092"
      - "9095:9093"
      - "9102:9102"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-mumbai:9093,2@kafka-pune:9093,3@kafka-delhi:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9102
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-pune:29092,EXTERNAL://localhost:9102
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      CLUSTER_ID: "XxLmcxwkQpieZydFQPRnzw"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-pune-data:/var/lib/kafka/data
    networks:
      - kafka-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - kafka-mumbai
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  kafka-delhi:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka-delhi
    ports:
      - "29094:29092"
      - "9097:9093"
      - "9103:9103"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-mumbai:9093,2@kafka-pune:9093,3@kafka-delhi:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9103
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-delhi:29092,EXTERNAL://localhost:9103
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      CLUSTER_ID: "XxLmcxwkQpieZydFQPRnzw"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-delhi-data:/var/lib/kafka/data
    networks:
      - kafka-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - kafka-mumbai
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  kafka-network:
    external: true

volumes:
  kafka-mumbai-data:
    external: true
  kafka-pune-data:
    external: true
  kafka-delhi-data:
    external: true
