version: '3.8'

services:
  kafka-mumbai:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka-mumbai
    ports:
      - "29092:29092"
      - "9093:9093"  
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-mumbai:9093,2@kafka-pune:9093,3@kafka-delhi:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9101
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-mumbai:29092,EXTERNAL://localhost:9101
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      CLUSTER_ID: "XxLmcxwkQpieZydFQPRnzw"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-mumbai-data:/var/lib/kafka/data
    networks:
      - kafka-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  kafka-pune:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka-pune
    ports:
      - "29093:29092"
      - "9095:9093"
      - "9102:9102"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-mumbai:9093,2@kafka-pune:9093,3@kafka-delhi:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9102
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-pune:29092,EXTERNAL://localhost:9102
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      CLUSTER_ID: "XxLmcxwkQpieZydFQPRnzw"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-pune-data:/var/lib/kafka/data
    networks:
      - kafka-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - kafka-mumbai

  kafka-delhi:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka-delhi
    ports:
      - "29094:29092"
      - "9097:9093"
      - "9103:9103"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-mumbai:9093,2@kafka-pune:9093,3@kafka-delhi:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9103
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-delhi:29092,EXTERNAL://localhost:9103
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      CLUSTER_ID: "XxLmcxwkQpieZydFQPRnzw"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-delhi-data:/var/lib/kafka/data
    networks:
      - kafka-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - kafka-mumbai

  kafka-topics-init:
    image: confluentinc/cp-kafka:7.5.1
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "
      echo 'Waiting for Kafka to be ready...'
      sleep 45
      echo 'Creating topics...'
      kafka-topics --bootstrap-server kafka-mumbai:29092 --create --if-not-exists --topic mumbai-locations --partitions 3 --replication-factor 3
      kafka-topics --bootstrap-server kafka-mumbai:29092 --create --if-not-exists --topic pune-locations --partitions 3 --replication-factor 3
      kafka-topics --bootstrap-server kafka-mumbai:29092 --create --if-not-exists --topic delhi-locations --partitions 3 --replication-factor 3
      echo 'Topics created!'
      exit 0
      "
    networks:
      - kafka-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - kafka-mumbai
      - kafka-pune
      - kafka-delhi

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: multi-region-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-mumbai:29092,kafka-pune:29092,kafka-delhi:29092"
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
    networks:
      - kafka-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - kafka-mumbai
      - kafka-pune
      - kafka-delhi
  
  producer:
    image: producer-service:latest
    ports:
      - "6969:6969"
    depends_on:
      - kafka-mumbai
      - kafka-pune
      - kafka-delhi
    environment:
      - KAFKA_BROKERS=kafka-mumbai:29092,kafka-pune:29092,kafka-delhi:29092
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 2
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    networks:
      - kafka-network

  consumer:
    image: consumer-service:latest
    depends_on:
      - kafka-mumbai
      - kafka-pune
      - kafka-delhi
    environment:
      - KAFKA_BROKERS=kafka-mumbai:29092,kafka-pune:29092,kafka-delhi:29092
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 2
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    networks:
      - kafka-network

  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: overlay
    attachable: true

volumes:
  kafka-mumbai-data:
  kafka-pune-data:
  kafka-delhi-data:
