services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]
    volumes:
      - "dynamodb-data:/home/dynamodblocal/data"
    networks:
      - kafka-network

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      AWS_REGION: local
      AWS_ACCESS_KEY_ID: localkey
      AWS_SECRET_ACCESS_KEY: localsecret
    depends_on:
      - dynamodb-local
    networks:
      - kafka-network

volumes:
  dynamodb-data:
  
networks:
  kafka-network:
    external: true
    name: kafka-network
